all:
  hosts:
    nexus-01:
      ansible_host: 147.45.215.248
    tc-agent:
      ansible_host: 147.45.215.213
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
