all:
  hosts:
    nexus-01:
      ansible_host: 5.129.192.8
    tc-agent:
      ansible_host: 5.129.192.68
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
