version: "3"
services:
  teamcity:
    image: jetbrains/teamcity-server
    user: root:root
    volumes:
      - ~/teamcity/data:/data/teamcity_server/datadir
      - ~/teamcity/logs:/opt/teamcity/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8111:8111
    privileged: true

  teamcity-agent:
    image: jetbrains/teamcity-agent
    user: root:root
    depends_on:
      - teamcity
    environment:
      SERVER_URL: "http://teamcity:8111"
    volumes:
      - ~/teamcity/agent:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
